### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mistzzt** [mistzzt/no-triton-you#1]
## Misc functions
- [ ] search-by-all
- [x] search-load-group-data
- [ ] search-get-section-text
- [ ] search-load-department
- [x] wr-logger
- [ ] change-enroll

## Library
- [x] Remove Phantomjs dependency

## App
- [ ] Android app plan
